import turtle

# 画脸
def drawFace():
    turtle.penup()
    turtle.goto(0, -100)
    turtle.pendown()
    turtle.fillcolor('#FFE4C4')
    turtle.begin_fill()
    turtle.circle(100)
    turtle.end_fill()

# 画眼睛
def drawEyes():
    turtle.penup()
    turtle.goto(-40, 20)
    turtle.pendown()
    turtle.fillcolor('white')
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(40, 20)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(20)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(-40, 30)
    turtle.pendown()
    turtle.fillcolor('black')
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()
    turtle.penup()
    turtle.goto(40, 30)
    turtle.pendown()
    turtle.begin_fill()
    turtle.circle(10)
    turtle.end_fill()

# 画嘴巴
def drawMouth():
    turtle.penup()
    turtle.goto(-30, -20)
    turtle.pendown()
    turtle.fillcolor('#FFC0CB')
    turtle.begin_fill()
    turtle.circle(30, 180)
    turtle.end_fill()

# 画头发
def drawHair():
    turtle.penup()
    turtle.goto(-80, 100)
    turtle.pendown()
    turtle.pensize(4)
    turtle.pencolor('black')
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)
    turtle.right(45)
    turtle.forward(50)

def main():
    turtle.setup(500, 500)
    turtle.speed(0)
    drawFace()
    drawEyes()
    drawMouth()
    drawHair()
    turtle.hideturtle()
    turtle.done()

if __name__ == '__main__':
    main()